dist: trusty
group: travis_latest

install:
  - sudo apt-get -y update
  - sudo apt-get install -y subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc wget unzip python

script:
  - bash -x ./build.sh

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  file: images/*
  skip-cleanup: true
  on:
    tags: true
#    condition: $NEW_BUILD = "Yes"
